config:
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd-demo
    source:
      repoURL: https://github.com/abrahamfsantoso/argocd-example-apps
      targetRevision: master

applications:
  - name: guestbook
    tool:
      helm:
        releaseName: guestbook